version: '3'


services:
  database1:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: l66-onyxiadb-local
      POSTGRES_PASSWORD: onyxia_pwd
      POSTGRES_USER: onyxia_usr
    volumes:
      - database_data1:/var/lib/postgresql/data:rw
  database2:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: l66-onyxiadb-local-test
      POSTGRES_PASSWORD: onyxia_test_pwd
      POSTGRES_USER: onyxia_test_usr
    volumes:
      - database_data2:/var/lib/postgresql/data:rw-
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  database_data1:
  database_data2: